---
abstract: 'Use Redis in Mojolicious'
author:
  - 'Meettya <meettya@gmail.com>'
build_requires:
  Module::Build: 0.36
  Mojolicious::Lite: 0
  Test::Mojo: 0
  Test::More: 0
  Try::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-Redis
provides:
  Mojolicious::Plugin::Redis:
    file: lib/Mojolicious/Plugin/Redis.pm
    version: 0.03
requires:
  Mojo::Base: 0
  Redis: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
